
[ja]
  title = "Shimpei.tk"
  LanguageName = "日本語"
  weight = 1
  [ja.params]
    introDescription = false
    dateFormat = "2006/01/02"

[en]
  title = "Shimpei.tk"
  LanguageName = "English"
  weight = 2
  [en.params]
    introDescription = false

[zh-TW]
  title = "Shimpei.tk"
  LanguageName = "中文"
  weight = 3
  [zh-TW.params]
    introDescription = false
    dateFormat = "2006/01/02"