
[ja]
  title = "Shimpei.tk"
  LanguageName = "日本語"
  weight = 1

[en]
  title = "Shimpei.tk"
  LanguageName = "English"
  weight = 2

[zh-TW]
  title = "Shimpei.tk"
  LanguageName = "中文"
  weight = 3