
[ja]
  title = "Shimpei.tk"
  LanguageName = "日本語"
  weight = 1
  [ja.params]
    introDescription = "静岡で蜜柑食べてます。"
    dateFormat = "2006/01/02"

[en]
  title = "Shimpei.tk"
  LanguageName = "English"
  weight = 2
  [en.params]
    introDescription = "I'm eating orange in Shizuoka."

[zh-TW]
  title = "Shimpei.tk"
  LanguageName = "中文"
  weight = 3
  [zh-TW.params]
    introDescription = "在靜岡吃橘子"
    dateFormat = "2006/01/02"